package eu.usrv.odib.init;

import cpw.mods.fml.common.registry.GameRegistry;
import eu.usrv.odib.blocks.*;
import eu.usrv.odib.help.RegisterHelper;
import net.minecraft.block.Block;
import net.minecraft.item.ItemStack;
import net.minecraftforge.oredict.OreDictionary;

public class ModBlocks {
	/*
	public static Block _AdamantiumBlock = new BlockBase("blockAdamantium");
	public static Block _AluminiumBlock = new BlockBase("blockAluminium");
	public static Block _AmericiumBlock = new BlockBase("blockAmericium");
	public static Block _AnnealedCopperBlock = new BlockBase("blockAnnealedCopper");
	public static Block _AntimonyBlock = new BlockBase("blockAntimony");
	public static Block _AstralSilverBlock = new BlockBase("blockAstralSilver");
	public static Block _BatteryAlloyBlock = new BlockBase("blockBatteryAlloy");
	public static Block _BerylliumBlock = new BlockBase("blockBeryllium");
	public static Block _BismuthBronzeBlock = new BlockBase("blockBismuthBronze");
	public static Block _BismuthBlock = new BlockBase("blockBismuth");
	public static Block _BlackBronzeBlock = new BlockBase("blockBlackBronze");
	public static Block _BlackSteelBlock = new BlockBase("blockBlackSteel");
	public static Block _BlueAlloyBlock = new BlockBase("blockBlueAlloy");
	public static Block _BlueSteelBlock = new BlockBase("blockBlueSteel");
	public static Block _BrassBlock = new BlockBase("blockBrass");
	public static Block _BronzeBlock = new BlockBase("blockBronze");
	public static Block _CaesiumBlock = new BlockBase("blockCaesium");
	public static Block _CeriumBlock = new BlockBase("blockCerium");
	public static Block _ChromeBlock = new BlockBase("blockChrome");
	public static Block _ChromiumDioxideBlock = new BlockBase("blockChromiumDioxide");
	public static Block _CobaltBrassBlock = new BlockBase("blockCobaltBrass");
	public static Block _CobaltBlock = new BlockBase("blockCobalt");
	public static Block _CopperBlock = new BlockBase("blockCopper");
	public static Block _CupronickelBlock = new BlockBase("blockCupronickel");
	public static Block _DamascusSteelBlock = new BlockBase("blockDamascusSteel");
	public static Block _DarkIronBlock = new BlockBase("blockDarkIron");
	public static Block _DeepIronBlock = new BlockBase("blockDeepIron");
	public static Block _DeshBlock = new BlockBase("blockDesh");
	public static Block _DuraniumBlock = new BlockBase("blockDuranium");
	public static Block _DysprosiumBlock = new BlockBase("blockDysprosium");
	public static Block _ElectrumFluxBlock = new BlockBase("blockElectrumFlux");
	public static Block _ElectrumBlock = new BlockBase("blockElectrum");
	public static Block _EnderiumBlock = new BlockBase("blockEnderium");
	public static Block _ErbiumBlock = new BlockBase("blockErbium");
	public static Block _EuropiumBlock = new BlockBase("blockEuropium");
	public static Block _FierySteelBlock = new BlockBase("blockFierySteel");
	public static Block _ForceBlock = new BlockBase("blockForce");
	public static Block _GadoliniumBlock = new BlockBase("blockGadolinium");
	public static Block _GalliumBlock = new BlockBase("blockGallium");
	public static Block _GoldBlock = new BlockBase("blockGold");
	public static Block _HSLABlock = new BlockBase("blockHSLA");
	public static Block _HolmiumBlock = new BlockBase("blockHolmium");
	public static Block _IndiumBlock = new BlockBase("blockIndium");
	public static Block _InfusedGoldBlock = new BlockBase("blockInfusedGold");
	public static Block _InvarBlock = new BlockBase("blockInvar");
	public static Block _IridiumBlock = new BlockBase("blockIridium");
	public static Block _IronMagneticBlock = new BlockBase("blockIronMagnetic");
	public static Block _IronWoodBlock = new BlockBase("blockIronWood");
	public static Block _IronBlock = new BlockBase("blockIron");
	public static Block _KanthalBlock = new BlockBase("blockKanthal");
	public static Block _KnightmetalBlock = new BlockBase("blockKnightmetal");
	public static Block _LanthanumBlock = new BlockBase("blockLanthanum");
	public static Block _LeadBlock = new BlockBase("blockLead");
	public static Block _LutetiumBlock = new BlockBase("blockLutetium");
	public static Block _MagnaliumBlock = new BlockBase("blockMagnalium");
	public static Block _MagnesiumBlock = new BlockBase("blockMagnesium");
	public static Block _ManganeseBlock = new BlockBase("blockManganese");
	public static Block _MeteoricIronBlock = new BlockBase("blockMeteoricIron");
	public static Block _MeteoricSteelBlock = new BlockBase("blockMeteoricSteel");
	public static Block _MidasiumBlock = new BlockBase("blockMidasium");
	public static Block _MithrilBlock = new BlockBase("blockMithril");
	public static Block _MolybdenumBlock = new BlockBase("blockMolybdenum");
	public static Block _NaquadahAlloyBlock = new BlockBase("blockNaquadahAlloy");
	public static Block _NaquadahEnrichedBlock = new BlockBase("blockNaquadahEnriched");
	public static Block _NaquadahBlock = new BlockBase("blockNaquadah");
	public static Block _NaquadriaBlock = new BlockBase("blockNaquadria");
	public static Block _NeodymiumMagneticBlock = new BlockBase("blockNeodymiumMagnetic");
	public static Block _NeodymiumBlock = new BlockBase("blockNeodymium");
	public static Block _NeutroniumBlock = new BlockBase("blockNeutronium");
	public static Block _NichromeBlock = new BlockBase("blockNichrome");
	public static Block _NickelBlock = new BlockBase("blockNickel");
	public static Block _NiobiumNitrideBlock = new BlockBase("blockNiobiumNitride");
	public static Block _NiobiumTitaniumBlock = new BlockBase("blockNiobiumTitanium");
	public static Block _NiobiumBlock = new BlockBase("blockNiobium");
	public static Block _OsmiridiumBlock = new BlockBase("blockOsmiridium");
	public static Block _OsmiumBlock = new BlockBase("blockOsmium");
	public static Block _PalladiumBlock = new BlockBase("blockPalladium");
	public static Block _PigIronBlock = new BlockBase("blockPigIron");
	public static Block _PlatinumBlock = new BlockBase("blockPlatinum");
	public static Block _Plutonium241Block = new BlockBase("blockPlutonium241");
	public static Block _PlutoniumBlock = new BlockBase("blockPlutonium");
	public static Block _PraseodymiumBlock = new BlockBase("blockPraseodymium");
	public static Block _PromethiumBlock = new BlockBase("blockPromethium");
	public static Block _RedAlloyBlock = new BlockBase("blockRedAlloy");
	public static Block _RedSteelBlock = new BlockBase("blockRedSteel");
	public static Block _RoseGoldBlock = new BlockBase("blockRoseGold");
	public static Block _RubidiumBlock = new BlockBase("blockRubidium");
	public static Block _SamariumBlock = new BlockBase("blockSamarium");
	public static Block _ScandiumBlock = new BlockBase("blockScandium");
	public static Block _ShadowIronBlock = new BlockBase("blockShadowIron");
	public static Block _ShadowSteelBlock = new BlockBase("blockShadowSteel");
	public static Block _SiliconBlock = new BlockBase("blockSilicon");
	public static Block _SilverBlock = new BlockBase("blockSilver");
	public static Block _SolderingAlloyBlock = new BlockBase("blockSolderingAlloy");
	public static Block _StainlessSteelBlock = new BlockBase("blockStainlessSteel");
	public static Block _SteelMagneticBlock = new BlockBase("blockSteelMagnetic");
	public static Block _SteelBlock = new BlockBase("blockSteel");
	public static Block _SteeleafBlock = new BlockBase("blockSteeleaf");
	public static Block _SterlingSilverBlock = new BlockBase("blockSterlingSilver");
	public static Block _SunnariumBlock = new BlockBase("blockSunnarium");
	public static Block _TantalumBlock = new BlockBase("blockTantalum");
	public static Block _TelluriumBlock = new BlockBase("blockTellurium");
	public static Block _TerbiumBlock = new BlockBase("blockTerbium");
	public static Block _ThaumiumBlock = new BlockBase("blockThaumium");
	public static Block _ThoriumBlock = new BlockBase("blockThorium");
	public static Block _ThuliumBlock = new BlockBase("blockThulium");
	public static Block _TinAlloyBlock = new BlockBase("blockTinAlloy");
	public static Block _TinBlock = new BlockBase("blockTin");
	public static Block _TitaniumBlock = new BlockBase("blockTitanium");
	public static Block _TritaniumBlock = new BlockBase("blockTritanium");
	public static Block _TungstenSteelBlock = new BlockBase("blockTungstenSteel");
	public static Block _TungstenBlock = new BlockBase("blockTungsten");
	public static Block _UltimetBlock = new BlockBase("blockUltimet");
	public static Block _Uranium235Block = new BlockBase("blockUranium235");
	public static Block _UraniumBlock = new BlockBase("blockUranium");
	public static Block _VanadiumGalliumBlock = new BlockBase("blockVanadiumGallium");
	public static Block _VanadiumBlock = new BlockBase("blockVanadium");
	public static Block _WroughtIronBlock = new BlockBase("blockWroughtIron");
	public static Block _YtterbiumBlock = new BlockBase("blockYtterbium");
	public static Block _YttriumBariumCuprateBlock = new BlockBase("blockYttriumBariumCuprate");
	public static Block _YttriumBlock = new BlockBase("blockYttrium");
	public static Block _ZincBlock = new BlockBase("blockZinc");
	public static Block _FieryBloodBlock = new BlockBase("blockFieryBlood");
	public static Block _MeatRawBlock = new BlockBase("blockMeatRaw");
	public static Block _PlasticBlock = new BlockBase("blockPlastic");
	public static Block _RubberBlock = new BlockBase("blockRubber");
	public static Block _SteelLeafBlock = new BlockBase("blockSteelLeaf");
	*/
    public static void init()
    {
    	InitBlocks();
    	RegisterBlocks();
    }
    
    private static void InitBlocks()
    {
/*    	RegisterHelper.registerBlock(_AdamantiumBlock);
    	RegisterHelper.registerBlock(_AluminiumBlock);
    	RegisterHelper.registerBlock(_AmericiumBlock);
    	RegisterHelper.registerBlock(_AnnealedCopperBlock);
    	RegisterHelper.registerBlock(_AntimonyBlock);
    	RegisterHelper.registerBlock(_AstralSilverBlock);
    	RegisterHelper.registerBlock(_BatteryAlloyBlock);
    	RegisterHelper.registerBlock(_BerylliumBlock);
    	RegisterHelper.registerBlock(_BismuthBronzeBlock);
    	RegisterHelper.registerBlock(_BismuthBlock);
    	RegisterHelper.registerBlock(_BlackBronzeBlock);
    	RegisterHelper.registerBlock(_BlackSteelBlock);
    	RegisterHelper.registerBlock(_BlueAlloyBlock);
    	RegisterHelper.registerBlock(_BlueSteelBlock);
    	RegisterHelper.registerBlock(_BrassBlock);
    	RegisterHelper.registerBlock(_BronzeBlock);
    	RegisterHelper.registerBlock(_CaesiumBlock);
    	RegisterHelper.registerBlock(_CeriumBlock);
    	RegisterHelper.registerBlock(_ChromeBlock);
    	RegisterHelper.registerBlock(_ChromiumDioxideBlock);
    	RegisterHelper.registerBlock(_CobaltBrassBlock);
    	RegisterHelper.registerBlock(_CobaltBlock);
    	RegisterHelper.registerBlock(_CopperBlock);
    	RegisterHelper.registerBlock(_CupronickelBlock);
    	RegisterHelper.registerBlock(_DamascusSteelBlock);
    	RegisterHelper.registerBlock(_DarkIronBlock);
    	RegisterHelper.registerBlock(_DeepIronBlock);
    	RegisterHelper.registerBlock(_DeshBlock);
    	RegisterHelper.registerBlock(_DuraniumBlock);
    	RegisterHelper.registerBlock(_DysprosiumBlock);
    	RegisterHelper.registerBlock(_ElectrumFluxBlock);
    	RegisterHelper.registerBlock(_ElectrumBlock);
    	RegisterHelper.registerBlock(_EnderiumBlock);
    	RegisterHelper.registerBlock(_ErbiumBlock);
    	RegisterHelper.registerBlock(_EuropiumBlock);
    	RegisterHelper.registerBlock(_FierySteelBlock);
    	RegisterHelper.registerBlock(_ForceBlock);
    	RegisterHelper.registerBlock(_GadoliniumBlock);
    	RegisterHelper.registerBlock(_GalliumBlock);
    	RegisterHelper.registerBlock(_GoldBlock);
    	RegisterHelper.registerBlock(_HSLABlock);
    	RegisterHelper.registerBlock(_HolmiumBlock);
    	RegisterHelper.registerBlock(_IndiumBlock);
    	RegisterHelper.registerBlock(_InfusedGoldBlock);
    	RegisterHelper.registerBlock(_InvarBlock);
    	RegisterHelper.registerBlock(_IridiumBlock);
    	RegisterHelper.registerBlock(_IronMagneticBlock);
    	RegisterHelper.registerBlock(_IronWoodBlock);
    	RegisterHelper.registerBlock(_IronBlock);
    	RegisterHelper.registerBlock(_KanthalBlock);
    	RegisterHelper.registerBlock(_KnightmetalBlock);
    	RegisterHelper.registerBlock(_LanthanumBlock);
    	RegisterHelper.registerBlock(_LeadBlock);
    	RegisterHelper.registerBlock(_LutetiumBlock);
    	RegisterHelper.registerBlock(_MagnaliumBlock);
    	RegisterHelper.registerBlock(_MagnesiumBlock);
    	RegisterHelper.registerBlock(_ManganeseBlock);
    	RegisterHelper.registerBlock(_MeteoricIronBlock);
    	RegisterHelper.registerBlock(_MeteoricSteelBlock);
    	RegisterHelper.registerBlock(_MidasiumBlock);
    	RegisterHelper.registerBlock(_MithrilBlock);
    	RegisterHelper.registerBlock(_MolybdenumBlock);
    	RegisterHelper.registerBlock(_NaquadahAlloyBlock);
    	RegisterHelper.registerBlock(_NaquadahEnrichedBlock);
    	RegisterHelper.registerBlock(_NaquadahBlock);
    	RegisterHelper.registerBlock(_NaquadriaBlock);
    	RegisterHelper.registerBlock(_NeodymiumMagneticBlock);
    	RegisterHelper.registerBlock(_NeodymiumBlock);
    	RegisterHelper.registerBlock(_NeutroniumBlock);
    	RegisterHelper.registerBlock(_NichromeBlock);
    	RegisterHelper.registerBlock(_NickelBlock);
    	RegisterHelper.registerBlock(_NiobiumNitrideBlock);
    	RegisterHelper.registerBlock(_NiobiumTitaniumBlock);
    	RegisterHelper.registerBlock(_NiobiumBlock);
    	RegisterHelper.registerBlock(_OsmiridiumBlock);
    	RegisterHelper.registerBlock(_OsmiumBlock);
    	RegisterHelper.registerBlock(_PalladiumBlock);
    	RegisterHelper.registerBlock(_PigIronBlock);
    	RegisterHelper.registerBlock(_PlatinumBlock);
    	RegisterHelper.registerBlock(_Plutonium241Block);
    	RegisterHelper.registerBlock(_PlutoniumBlock);
    	RegisterHelper.registerBlock(_PraseodymiumBlock);
    	RegisterHelper.registerBlock(_PromethiumBlock);
    	RegisterHelper.registerBlock(_RedAlloyBlock);
    	RegisterHelper.registerBlock(_RedSteelBlock);
    	RegisterHelper.registerBlock(_RoseGoldBlock);
    	RegisterHelper.registerBlock(_RubidiumBlock);
    	RegisterHelper.registerBlock(_SamariumBlock);
    	RegisterHelper.registerBlock(_ScandiumBlock);
    	RegisterHelper.registerBlock(_ShadowIronBlock);
    	RegisterHelper.registerBlock(_ShadowSteelBlock);
    	RegisterHelper.registerBlock(_SiliconBlock);
    	RegisterHelper.registerBlock(_SilverBlock);
    	RegisterHelper.registerBlock(_SolderingAlloyBlock);
    	RegisterHelper.registerBlock(_StainlessSteelBlock);
    	RegisterHelper.registerBlock(_SteelMagneticBlock);
    	RegisterHelper.registerBlock(_SteelBlock);
    	RegisterHelper.registerBlock(_SteeleafBlock);
    	RegisterHelper.registerBlock(_SterlingSilverBlock);
    	RegisterHelper.registerBlock(_SunnariumBlock);
    	RegisterHelper.registerBlock(_TantalumBlock);
    	RegisterHelper.registerBlock(_TelluriumBlock);
    	RegisterHelper.registerBlock(_TerbiumBlock);
    	RegisterHelper.registerBlock(_ThaumiumBlock);
    	RegisterHelper.registerBlock(_ThoriumBlock);
    	RegisterHelper.registerBlock(_ThuliumBlock);
    	RegisterHelper.registerBlock(_TinAlloyBlock);
    	RegisterHelper.registerBlock(_TinBlock);
    	RegisterHelper.registerBlock(_TitaniumBlock);
    	RegisterHelper.registerBlock(_TritaniumBlock);
    	RegisterHelper.registerBlock(_TungstenSteelBlock);
    	RegisterHelper.registerBlock(_TungstenBlock);
    	RegisterHelper.registerBlock(_UltimetBlock);
    	RegisterHelper.registerBlock(_Uranium235Block);
    	RegisterHelper.registerBlock(_UraniumBlock);
    	RegisterHelper.registerBlock(_VanadiumGalliumBlock);
    	RegisterHelper.registerBlock(_VanadiumBlock);
    	RegisterHelper.registerBlock(_WroughtIronBlock);
    	RegisterHelper.registerBlock(_YtterbiumBlock);
    	RegisterHelper.registerBlock(_YttriumBariumCuprateBlock);
    	RegisterHelper.registerBlock(_YttriumBlock);
    	RegisterHelper.registerBlock(_ZincBlock);
    	RegisterHelper.registerBlock(_FieryBloodBlock);
    	RegisterHelper.registerBlock(_MeatRawBlock);
    	RegisterHelper.registerBlock(_PlasticBlock);
    	RegisterHelper.registerBlock(_RubberBlock);
    	RegisterHelper.registerBlock(_SteelLeafBlock);
*/
    }
    public static Block Blocks_A = new Blocks_A();
    
    private static void RegisterBlocks()
    {
    	GameRegistry.registerBlock(Blocks_A, "Block of ");
    	
    	
    	/*
    	OreDictionary.registerOre("blockAdamantium", new ItemStack(_AdamantiumBlock, 1, 1));
    	OreDictionary.registerOre("blockAluminium", new ItemStack(_AluminiumBlock, 1, 2));
    	OreDictionary.registerOre("blockAmericium", new ItemStack(_AmericiumBlock, 1, 3));
    	OreDictionary.registerOre("blockAnnealedCopper", new ItemStack(_AnnealedCopperBlock, 1, 4));
    	OreDictionary.registerOre("blockAntimony", new ItemStack(_AntimonyBlock, 1, 5));
    	OreDictionary.registerOre("blockAstralSilver", new ItemStack(_AstralSilverBlock, 1, 6));
    	OreDictionary.registerOre("blockBatteryAlloy", new ItemStack(_BatteryAlloyBlock, 1, 7));
    	OreDictionary.registerOre("blockBeryllium", new ItemStack(_BerylliumBlock, 1, 8));
    	OreDictionary.registerOre("blockBismuthBronze", new ItemStack(_BismuthBronzeBlock, 1, 9));
    	OreDictionary.registerOre("blockBismuth", new ItemStack(_BismuthBlock, 1, 10));
    	OreDictionary.registerOre("blockBlackBronze", new ItemStack(_BlackBronzeBlock, 1, 11));
    	OreDictionary.registerOre("blockBlackSteel", new ItemStack(_BlackSteelBlock, 1, 12));
    	OreDictionary.registerOre("blockBlueAlloy", new ItemStack(_BlueAlloyBlock, 1, 13));
    	OreDictionary.registerOre("blockBlueSteel", new ItemStack(_BlueSteelBlock, 1, 14));
    	OreDictionary.registerOre("blockBrass", new ItemStack(_BrassBlock, 1, 15));
    	OreDictionary.registerOre("blockBronze", new ItemStack(_BronzeBlock, 1, 16));
    	OreDictionary.registerOre("blockCaesium", new ItemStack(_CaesiumBlock, 1, 17));
    	OreDictionary.registerOre("blockCerium", new ItemStack(_CeriumBlock, 1, 18));
    	OreDictionary.registerOre("blockChrome", new ItemStack(_ChromeBlock, 1, 19));
    	OreDictionary.registerOre("blockChromiumDioxide", new ItemStack(_ChromiumDioxideBlock, 1, 20));
    	OreDictionary.registerOre("blockCobaltBrass", new ItemStack(_CobaltBrassBlock, 1, 21));
    	OreDictionary.registerOre("blockCobalt", new ItemStack(_CobaltBlock, 1, 22));
    	OreDictionary.registerOre("blockCopper", new ItemStack(_CopperBlock, 1, 23));
    	OreDictionary.registerOre("blockCupronickel", new ItemStack(_CupronickelBlock, 1, 24));
    	OreDictionary.registerOre("blockDamascusSteel", new ItemStack(_DamascusSteelBlock, 1, 25));
    	OreDictionary.registerOre("blockDarkIron", new ItemStack(_DarkIronBlock, 1, 26));
    	OreDictionary.registerOre("blockDeepIron", new ItemStack(_DeepIronBlock, 1, 27));
    	OreDictionary.registerOre("blockDesh", new ItemStack(_DeshBlock, 1, 28));
    	OreDictionary.registerOre("blockDuranium", new ItemStack(_DuraniumBlock, 1, 29));
    	OreDictionary.registerOre("blockDysprosium", new ItemStack(_DysprosiumBlock, 1, 30));
    	OreDictionary.registerOre("blockElectrumFlux", new ItemStack(_ElectrumFluxBlock, 1, 31));
    	OreDictionary.registerOre("blockElectrum", new ItemStack(_ElectrumBlock, 1, 32));
    	OreDictionary.registerOre("blockEnderium", new ItemStack(_EnderiumBlock, 1, 33));
    	OreDictionary.registerOre("blockErbium", new ItemStack(_ErbiumBlock, 1, 34));
    	OreDictionary.registerOre("blockEuropium", new ItemStack(_EuropiumBlock, 1, 35));
    	OreDictionary.registerOre("blockFierySteel", new ItemStack(_FierySteelBlock, 1, 36));
    	OreDictionary.registerOre("blockForce", new ItemStack(_ForceBlock, 1, 37));
    	OreDictionary.registerOre("blockGadolinium", new ItemStack(_GadoliniumBlock, 1, 38));
    	OreDictionary.registerOre("blockGallium", new ItemStack(_GalliumBlock, 1, 39));
    	OreDictionary.registerOre("blockGold", new ItemStack(_GoldBlock, 1, 40));
    	OreDictionary.registerOre("blockHSLA", new ItemStack(_HSLABlock, 1, 41));
    	OreDictionary.registerOre("blockHolmium", new ItemStack(_HolmiumBlock, 1, 42));
    	OreDictionary.registerOre("blockIndium", new ItemStack(_IndiumBlock, 1, 43));
    	OreDictionary.registerOre("blockInfusedGold", new ItemStack(_InfusedGoldBlock, 1, 44));
    	OreDictionary.registerOre("blockInvar", new ItemStack(_InvarBlock, 1, 45));
    	OreDictionary.registerOre("blockIridium", new ItemStack(_IridiumBlock, 1, 46));
    	OreDictionary.registerOre("blockIronMagnetic", new ItemStack(_IronMagneticBlock, 1, 47));
    	OreDictionary.registerOre("blockIronWood", new ItemStack(_IronWoodBlock, 1, 48));
    	OreDictionary.registerOre("blockIron", new ItemStack(_IronBlock, 1, 49));
    	OreDictionary.registerOre("blockKanthal", new ItemStack(_KanthalBlock, 1, 50));
    	OreDictionary.registerOre("blockKnightmetal", new ItemStack(_KnightmetalBlock, 1, 51));
    	OreDictionary.registerOre("blockLanthanum", new ItemStack(_LanthanumBlock, 1, 52));
    	OreDictionary.registerOre("blockLead", new ItemStack(_LeadBlock, 1, 53));
    	OreDictionary.registerOre("blockLutetium", new ItemStack(_LutetiumBlock, 1, 54));
    	OreDictionary.registerOre("blockMagnalium", new ItemStack(_MagnaliumBlock, 1, 55));
    	OreDictionary.registerOre("blockMagnesium", new ItemStack(_MagnesiumBlock, 1, 56));
    	OreDictionary.registerOre("blockManganese", new ItemStack(_ManganeseBlock, 1, 57));
    	OreDictionary.registerOre("blockMeteoricIron", new ItemStack(_MeteoricIronBlock, 1, 58));
    	OreDictionary.registerOre("blockMeteoricSteel", new ItemStack(_MeteoricSteelBlock, 1, 59));
    	OreDictionary.registerOre("blockMidasium", new ItemStack(_MidasiumBlock, 1, 60));
    	OreDictionary.registerOre("blockMithril", new ItemStack(_MithrilBlock, 1, 61));
    	OreDictionary.registerOre("blockMolybdenum", new ItemStack(_MolybdenumBlock, 1, 62));
    	OreDictionary.registerOre("blockNaquadahAlloy", new ItemStack(_NaquadahAlloyBlock, 1, 63));
    	OreDictionary.registerOre("blockNaquadahEnriched", new ItemStack(_NaquadahEnrichedBlock, 1, 64));
    	OreDictionary.registerOre("blockNaquadah", new ItemStack(_NaquadahBlock, 1, 65));
    	OreDictionary.registerOre("blockNaquadria", new ItemStack(_NaquadriaBlock, 1, 66));
    	OreDictionary.registerOre("blockNeodymiumMagnetic", new ItemStack(_NeodymiumMagneticBlock, 1, 67));
    	OreDictionary.registerOre("blockNeodymium", new ItemStack(_NeodymiumBlock, 1, 68));
    	OreDictionary.registerOre("blockNeutronium", new ItemStack(_NeutroniumBlock, 1, 69));
    	OreDictionary.registerOre("blockNichrome", new ItemStack(_NichromeBlock, 1, 70));
    	OreDictionary.registerOre("blockNickel", new ItemStack(_NickelBlock, 1, 71));
    	OreDictionary.registerOre("blockNiobiumNitride", new ItemStack(_NiobiumNitrideBlock, 1, 72));
    	OreDictionary.registerOre("blockNiobiumTitanium", new ItemStack(_NiobiumTitaniumBlock, 1, 73));
    	OreDictionary.registerOre("blockNiobium", new ItemStack(_NiobiumBlock, 1, 74));
    	OreDictionary.registerOre("blockOsmiridium", new ItemStack(_OsmiridiumBlock, 1, 75));
    	OreDictionary.registerOre("blockOsmium", new ItemStack(_OsmiumBlock, 1, 76));
    	OreDictionary.registerOre("blockPalladium", new ItemStack(_PalladiumBlock, 1, 77));
    	OreDictionary.registerOre("blockPigIron", new ItemStack(_PigIronBlock, 1, 78));
    	OreDictionary.registerOre("blockPlatinum", new ItemStack(_PlatinumBlock, 1, 79));
    	OreDictionary.registerOre("blockPlutonium241", new ItemStack(_Plutonium241Block, 1, 80));
    	OreDictionary.registerOre("blockPlutonium", new ItemStack(_PlutoniumBlock, 1, 81));
    	OreDictionary.registerOre("blockPraseodymium", new ItemStack(_PraseodymiumBlock, 1, 82));
    	OreDictionary.registerOre("blockPromethium", new ItemStack(_PromethiumBlock, 1, 83));
    	OreDictionary.registerOre("blockRedAlloy", new ItemStack(_RedAlloyBlock, 1, 84));
    	OreDictionary.registerOre("blockRedSteel", new ItemStack(_RedSteelBlock, 1, 85));
    	OreDictionary.registerOre("blockRoseGold", new ItemStack(_RoseGoldBlock, 1, 86));
    	OreDictionary.registerOre("blockRubidium", new ItemStack(_RubidiumBlock, 1, 87));
    	OreDictionary.registerOre("blockSamarium", new ItemStack(_SamariumBlock, 1, 88));
    	OreDictionary.registerOre("blockScandium", new ItemStack(_ScandiumBlock, 1, 89));
    	OreDictionary.registerOre("blockShadowIron", new ItemStack(_ShadowIronBlock, 1, 90));
    	OreDictionary.registerOre("blockShadowSteel", new ItemStack(_ShadowSteelBlock, 1, 91));
    	OreDictionary.registerOre("blockSilicon", new ItemStack(_SiliconBlock, 1, 92));
    	OreDictionary.registerOre("blockSilver", new ItemStack(_SilverBlock, 1, 93));
    	OreDictionary.registerOre("blockSolderingAlloy", new ItemStack(_SolderingAlloyBlock, 1, 94));
    	OreDictionary.registerOre("blockStainlessSteel", new ItemStack(_StainlessSteelBlock, 1, 95));
    	OreDictionary.registerOre("blockSteelMagnetic", new ItemStack(_SteelMagneticBlock, 1, 96));
    	OreDictionary.registerOre("blockSteel", new ItemStack(_SteelBlock, 1, 97));
    	OreDictionary.registerOre("blockSteeleaf", new ItemStack(_SteeleafBlock, 1, 98));
    	OreDictionary.registerOre("blockSterlingSilver", new ItemStack(_SterlingSilverBlock, 1, 99));
    	OreDictionary.registerOre("blockSunnarium", new ItemStack(_SunnariumBlock, 1, 100));
    	OreDictionary.registerOre("blockTantalum", new ItemStack(_TantalumBlock, 1, 101));
    	OreDictionary.registerOre("blockTellurium", new ItemStack(_TelluriumBlock, 1, 102));
    	OreDictionary.registerOre("blockTerbium", new ItemStack(_TerbiumBlock, 1, 103));
    	OreDictionary.registerOre("blockThaumium", new ItemStack(_ThaumiumBlock, 1, 104));
    	OreDictionary.registerOre("blockThorium", new ItemStack(_ThoriumBlock, 1, 105));
    	OreDictionary.registerOre("blockThulium", new ItemStack(_ThuliumBlock, 1, 106));
    	OreDictionary.registerOre("blockTinAlloy", new ItemStack(_TinAlloyBlock, 1, 107));
    	OreDictionary.registerOre("blockTin", new ItemStack(_TinBlock, 1, 108));
    	OreDictionary.registerOre("blockTitanium", new ItemStack(_TitaniumBlock, 1, 109));
    	OreDictionary.registerOre("blockTritanium", new ItemStack(_TritaniumBlock, 1, 110));
    	OreDictionary.registerOre("blockTungstenSteel", new ItemStack(_TungstenSteelBlock, 1, 111));
    	OreDictionary.registerOre("blockTungsten", new ItemStack(_TungstenBlock, 1, 112));
    	OreDictionary.registerOre("blockUltimet", new ItemStack(_UltimetBlock, 1, 113));
    	OreDictionary.registerOre("blockUranium235", new ItemStack(_Uranium235Block, 1, 114));
    	OreDictionary.registerOre("blockUranium", new ItemStack(_UraniumBlock, 1, 115));
    	OreDictionary.registerOre("blockVanadiumGallium", new ItemStack(_VanadiumGalliumBlock, 1, 116));
    	OreDictionary.registerOre("blockVanadium", new ItemStack(_VanadiumBlock, 1, 117));
    	OreDictionary.registerOre("blockWroughtIron", new ItemStack(_WroughtIronBlock, 1, 118));
    	OreDictionary.registerOre("blockYtterbium", new ItemStack(_YtterbiumBlock, 1, 119));
    	OreDictionary.registerOre("blockYttriumBariumCuprate", new ItemStack(_YttriumBariumCuprateBlock, 1, 120));
    	OreDictionary.registerOre("blockYttrium", new ItemStack(_YttriumBlock, 1, 121));
    	OreDictionary.registerOre("blockZinc", new ItemStack(_ZincBlock, 1, 122));
    	OreDictionary.registerOre("blockFieryBlood", new ItemStack(_FieryBloodBlock, 1, 123));
    	OreDictionary.registerOre("blockMeatRaw", new ItemStack(_MeatRawBlock, 1, 124));
    	OreDictionary.registerOre("blockPlastic", new ItemStack(_PlasticBlock, 1, 125));
    	OreDictionary.registerOre("blockRubber", new ItemStack(_RubberBlock, 1, 126));
    	OreDictionary.registerOre("blockSteelLeaf", new ItemStack(_SteelLeafBlock, 1, 127));
    	*/
    }
}
